// Code generated by ent, DO NOT EDIT.

package peakusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the peakusage type in the database.
	Label = "peak_usage"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldEntityType holds the string denoting the entity_type field in the database.
	FieldEntityType = "entity_type"
	// FieldEntityID holds the string denoting the entity_id field in the database.
	FieldEntityID = "entity_id"
	// FieldPeakConcurrency holds the string denoting the peak_concurrency field in the database.
	FieldPeakConcurrency = "peak_concurrency"
	// FieldPeakSessions holds the string denoting the peak_sessions field in the database.
	FieldPeakSessions = "peak_sessions"
	// FieldPeakRpm holds the string denoting the peak_rpm field in the database.
	FieldPeakRpm = "peak_rpm"
	// FieldResetAt holds the string denoting the reset_at field in the database.
	FieldResetAt = "reset_at"
	// Table holds the table name of the peakusage in the database.
	Table = "peak_usages"
)

// Columns holds all SQL columns for peakusage fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldEntityType,
	FieldEntityID,
	FieldPeakConcurrency,
	FieldPeakSessions,
	FieldPeakRpm,
	FieldResetAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// EntityTypeValidator is a validator for the "entity_type" field. It is called by the builders before save.
	EntityTypeValidator func(string) error
	// EntityIDValidator is a validator for the "entity_id" field. It is called by the builders before save.
	EntityIDValidator func(int64) error
	// DefaultPeakConcurrency holds the default value on creation for the "peak_concurrency" field.
	DefaultPeakConcurrency int
	// PeakConcurrencyValidator is a validator for the "peak_concurrency" field. It is called by the builders before save.
	PeakConcurrencyValidator func(int) error
	// DefaultPeakSessions holds the default value on creation for the "peak_sessions" field.
	DefaultPeakSessions int
	// PeakSessionsValidator is a validator for the "peak_sessions" field. It is called by the builders before save.
	PeakSessionsValidator func(int) error
	// DefaultPeakRpm holds the default value on creation for the "peak_rpm" field.
	DefaultPeakRpm int
	// PeakRpmValidator is a validator for the "peak_rpm" field. It is called by the builders before save.
	PeakRpmValidator func(int) error
)

// OrderOption defines the ordering options for the PeakUsage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByEntityType orders the results by the entity_type field.
func ByEntityType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityType, opts...).ToFunc()
}

// ByEntityID orders the results by the entity_id field.
func ByEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityID, opts...).ToFunc()
}

// ByPeakConcurrency orders the results by the peak_concurrency field.
func ByPeakConcurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeakConcurrency, opts...).ToFunc()
}

// ByPeakSessions orders the results by the peak_sessions field.
func ByPeakSessions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeakSessions, opts...).ToFunc()
}

// ByPeakRpm orders the results by the peak_rpm field.
func ByPeakRpm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeakRpm, opts...).ToFunc()
}

// ByResetAt orders the results by the reset_at field.
func ByResetAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResetAt, opts...).ToFunc()
}
