// Code generated by ent, DO NOT EDIT.

package peakusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldEQ(FieldUpdatedAt, v))
}

// EntityType applies equality check predicate on the "entity_type" field. It's identical to EntityTypeEQ.
func EntityType(v string) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldEQ(FieldEntityType, v))
}

// EntityID applies equality check predicate on the "entity_id" field. It's identical to EntityIDEQ.
func EntityID(v int64) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldEQ(FieldEntityID, v))
}

// PeakConcurrency applies equality check predicate on the "peak_concurrency" field. It's identical to PeakConcurrencyEQ.
func PeakConcurrency(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldEQ(FieldPeakConcurrency, v))
}

// PeakSessions applies equality check predicate on the "peak_sessions" field. It's identical to PeakSessionsEQ.
func PeakSessions(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldEQ(FieldPeakSessions, v))
}

// PeakRpm applies equality check predicate on the "peak_rpm" field. It's identical to PeakRpmEQ.
func PeakRpm(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldEQ(FieldPeakRpm, v))
}

// ResetAt applies equality check predicate on the "reset_at" field. It's identical to ResetAtEQ.
func ResetAt(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldEQ(FieldResetAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldLTE(FieldUpdatedAt, v))
}

// EntityTypeEQ applies the EQ predicate on the "entity_type" field.
func EntityTypeEQ(v string) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldEQ(FieldEntityType, v))
}

// EntityTypeNEQ applies the NEQ predicate on the "entity_type" field.
func EntityTypeNEQ(v string) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldNEQ(FieldEntityType, v))
}

// EntityTypeIn applies the In predicate on the "entity_type" field.
func EntityTypeIn(vs ...string) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldIn(FieldEntityType, vs...))
}

// EntityTypeNotIn applies the NotIn predicate on the "entity_type" field.
func EntityTypeNotIn(vs ...string) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldNotIn(FieldEntityType, vs...))
}

// EntityTypeGT applies the GT predicate on the "entity_type" field.
func EntityTypeGT(v string) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldGT(FieldEntityType, v))
}

// EntityTypeGTE applies the GTE predicate on the "entity_type" field.
func EntityTypeGTE(v string) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldGTE(FieldEntityType, v))
}

// EntityTypeLT applies the LT predicate on the "entity_type" field.
func EntityTypeLT(v string) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldLT(FieldEntityType, v))
}

// EntityTypeLTE applies the LTE predicate on the "entity_type" field.
func EntityTypeLTE(v string) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldLTE(FieldEntityType, v))
}

// EntityTypeContains applies the Contains predicate on the "entity_type" field.
func EntityTypeContains(v string) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldContains(FieldEntityType, v))
}

// EntityTypeHasPrefix applies the HasPrefix predicate on the "entity_type" field.
func EntityTypeHasPrefix(v string) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldHasPrefix(FieldEntityType, v))
}

// EntityTypeHasSuffix applies the HasSuffix predicate on the "entity_type" field.
func EntityTypeHasSuffix(v string) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldHasSuffix(FieldEntityType, v))
}

// EntityTypeEqualFold applies the EqualFold predicate on the "entity_type" field.
func EntityTypeEqualFold(v string) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldEqualFold(FieldEntityType, v))
}

// EntityTypeContainsFold applies the ContainsFold predicate on the "entity_type" field.
func EntityTypeContainsFold(v string) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldContainsFold(FieldEntityType, v))
}

// EntityIDEQ applies the EQ predicate on the "entity_id" field.
func EntityIDEQ(v int64) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldEQ(FieldEntityID, v))
}

// EntityIDNEQ applies the NEQ predicate on the "entity_id" field.
func EntityIDNEQ(v int64) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldNEQ(FieldEntityID, v))
}

// EntityIDIn applies the In predicate on the "entity_id" field.
func EntityIDIn(vs ...int64) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldIn(FieldEntityID, vs...))
}

// EntityIDNotIn applies the NotIn predicate on the "entity_id" field.
func EntityIDNotIn(vs ...int64) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldNotIn(FieldEntityID, vs...))
}

// EntityIDGT applies the GT predicate on the "entity_id" field.
func EntityIDGT(v int64) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldGT(FieldEntityID, v))
}

// EntityIDGTE applies the GTE predicate on the "entity_id" field.
func EntityIDGTE(v int64) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldGTE(FieldEntityID, v))
}

// EntityIDLT applies the LT predicate on the "entity_id" field.
func EntityIDLT(v int64) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldLT(FieldEntityID, v))
}

// EntityIDLTE applies the LTE predicate on the "entity_id" field.
func EntityIDLTE(v int64) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldLTE(FieldEntityID, v))
}

// PeakConcurrencyEQ applies the EQ predicate on the "peak_concurrency" field.
func PeakConcurrencyEQ(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldEQ(FieldPeakConcurrency, v))
}

// PeakConcurrencyNEQ applies the NEQ predicate on the "peak_concurrency" field.
func PeakConcurrencyNEQ(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldNEQ(FieldPeakConcurrency, v))
}

// PeakConcurrencyIn applies the In predicate on the "peak_concurrency" field.
func PeakConcurrencyIn(vs ...int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldIn(FieldPeakConcurrency, vs...))
}

// PeakConcurrencyNotIn applies the NotIn predicate on the "peak_concurrency" field.
func PeakConcurrencyNotIn(vs ...int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldNotIn(FieldPeakConcurrency, vs...))
}

// PeakConcurrencyGT applies the GT predicate on the "peak_concurrency" field.
func PeakConcurrencyGT(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldGT(FieldPeakConcurrency, v))
}

// PeakConcurrencyGTE applies the GTE predicate on the "peak_concurrency" field.
func PeakConcurrencyGTE(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldGTE(FieldPeakConcurrency, v))
}

// PeakConcurrencyLT applies the LT predicate on the "peak_concurrency" field.
func PeakConcurrencyLT(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldLT(FieldPeakConcurrency, v))
}

// PeakConcurrencyLTE applies the LTE predicate on the "peak_concurrency" field.
func PeakConcurrencyLTE(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldLTE(FieldPeakConcurrency, v))
}

// PeakSessionsEQ applies the EQ predicate on the "peak_sessions" field.
func PeakSessionsEQ(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldEQ(FieldPeakSessions, v))
}

// PeakSessionsNEQ applies the NEQ predicate on the "peak_sessions" field.
func PeakSessionsNEQ(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldNEQ(FieldPeakSessions, v))
}

// PeakSessionsIn applies the In predicate on the "peak_sessions" field.
func PeakSessionsIn(vs ...int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldIn(FieldPeakSessions, vs...))
}

// PeakSessionsNotIn applies the NotIn predicate on the "peak_sessions" field.
func PeakSessionsNotIn(vs ...int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldNotIn(FieldPeakSessions, vs...))
}

// PeakSessionsGT applies the GT predicate on the "peak_sessions" field.
func PeakSessionsGT(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldGT(FieldPeakSessions, v))
}

// PeakSessionsGTE applies the GTE predicate on the "peak_sessions" field.
func PeakSessionsGTE(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldGTE(FieldPeakSessions, v))
}

// PeakSessionsLT applies the LT predicate on the "peak_sessions" field.
func PeakSessionsLT(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldLT(FieldPeakSessions, v))
}

// PeakSessionsLTE applies the LTE predicate on the "peak_sessions" field.
func PeakSessionsLTE(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldLTE(FieldPeakSessions, v))
}

// PeakRpmEQ applies the EQ predicate on the "peak_rpm" field.
func PeakRpmEQ(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldEQ(FieldPeakRpm, v))
}

// PeakRpmNEQ applies the NEQ predicate on the "peak_rpm" field.
func PeakRpmNEQ(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldNEQ(FieldPeakRpm, v))
}

// PeakRpmIn applies the In predicate on the "peak_rpm" field.
func PeakRpmIn(vs ...int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldIn(FieldPeakRpm, vs...))
}

// PeakRpmNotIn applies the NotIn predicate on the "peak_rpm" field.
func PeakRpmNotIn(vs ...int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldNotIn(FieldPeakRpm, vs...))
}

// PeakRpmGT applies the GT predicate on the "peak_rpm" field.
func PeakRpmGT(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldGT(FieldPeakRpm, v))
}

// PeakRpmGTE applies the GTE predicate on the "peak_rpm" field.
func PeakRpmGTE(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldGTE(FieldPeakRpm, v))
}

// PeakRpmLT applies the LT predicate on the "peak_rpm" field.
func PeakRpmLT(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldLT(FieldPeakRpm, v))
}

// PeakRpmLTE applies the LTE predicate on the "peak_rpm" field.
func PeakRpmLTE(v int) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldLTE(FieldPeakRpm, v))
}

// ResetAtEQ applies the EQ predicate on the "reset_at" field.
func ResetAtEQ(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldEQ(FieldResetAt, v))
}

// ResetAtNEQ applies the NEQ predicate on the "reset_at" field.
func ResetAtNEQ(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldNEQ(FieldResetAt, v))
}

// ResetAtIn applies the In predicate on the "reset_at" field.
func ResetAtIn(vs ...time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldIn(FieldResetAt, vs...))
}

// ResetAtNotIn applies the NotIn predicate on the "reset_at" field.
func ResetAtNotIn(vs ...time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldNotIn(FieldResetAt, vs...))
}

// ResetAtGT applies the GT predicate on the "reset_at" field.
func ResetAtGT(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldGT(FieldResetAt, v))
}

// ResetAtGTE applies the GTE predicate on the "reset_at" field.
func ResetAtGTE(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldGTE(FieldResetAt, v))
}

// ResetAtLT applies the LT predicate on the "reset_at" field.
func ResetAtLT(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldLT(FieldResetAt, v))
}

// ResetAtLTE applies the LTE predicate on the "reset_at" field.
func ResetAtLTE(v time.Time) predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldLTE(FieldResetAt, v))
}

// ResetAtIsNil applies the IsNil predicate on the "reset_at" field.
func ResetAtIsNil() predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldIsNull(FieldResetAt))
}

// ResetAtNotNil applies the NotNil predicate on the "reset_at" field.
func ResetAtNotNil() predicate.PeakUsage {
	return predicate.PeakUsage(sql.FieldNotNull(FieldResetAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PeakUsage) predicate.PeakUsage {
	return predicate.PeakUsage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PeakUsage) predicate.PeakUsage {
	return predicate.PeakUsage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PeakUsage) predicate.PeakUsage {
	return predicate.PeakUsage(sql.NotPredicates(p))
}
