// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/peakusage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PeakUsageUpdate is the builder for updating PeakUsage entities.
type PeakUsageUpdate struct {
	config
	hooks    []Hook
	mutation *PeakUsageMutation
}

// Where appends a list predicates to the PeakUsageUpdate builder.
func (_u *PeakUsageUpdate) Where(ps ...predicate.PeakUsage) *PeakUsageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PeakUsageUpdate) SetUpdatedAt(v time.Time) *PeakUsageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *PeakUsageUpdate) SetEntityType(v string) *PeakUsageUpdate {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *PeakUsageUpdate) SetNillableEntityType(v *string) *PeakUsageUpdate {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *PeakUsageUpdate) SetEntityID(v int64) *PeakUsageUpdate {
	_u.mutation.ResetEntityID()
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *PeakUsageUpdate) SetNillableEntityID(v *int64) *PeakUsageUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// AddEntityID adds value to the "entity_id" field.
func (_u *PeakUsageUpdate) AddEntityID(v int64) *PeakUsageUpdate {
	_u.mutation.AddEntityID(v)
	return _u
}

// SetPeakConcurrency sets the "peak_concurrency" field.
func (_u *PeakUsageUpdate) SetPeakConcurrency(v int) *PeakUsageUpdate {
	_u.mutation.ResetPeakConcurrency()
	_u.mutation.SetPeakConcurrency(v)
	return _u
}

// SetNillablePeakConcurrency sets the "peak_concurrency" field if the given value is not nil.
func (_u *PeakUsageUpdate) SetNillablePeakConcurrency(v *int) *PeakUsageUpdate {
	if v != nil {
		_u.SetPeakConcurrency(*v)
	}
	return _u
}

// AddPeakConcurrency adds value to the "peak_concurrency" field.
func (_u *PeakUsageUpdate) AddPeakConcurrency(v int) *PeakUsageUpdate {
	_u.mutation.AddPeakConcurrency(v)
	return _u
}

// SetPeakSessions sets the "peak_sessions" field.
func (_u *PeakUsageUpdate) SetPeakSessions(v int) *PeakUsageUpdate {
	_u.mutation.ResetPeakSessions()
	_u.mutation.SetPeakSessions(v)
	return _u
}

// SetNillablePeakSessions sets the "peak_sessions" field if the given value is not nil.
func (_u *PeakUsageUpdate) SetNillablePeakSessions(v *int) *PeakUsageUpdate {
	if v != nil {
		_u.SetPeakSessions(*v)
	}
	return _u
}

// AddPeakSessions adds value to the "peak_sessions" field.
func (_u *PeakUsageUpdate) AddPeakSessions(v int) *PeakUsageUpdate {
	_u.mutation.AddPeakSessions(v)
	return _u
}

// SetPeakRpm sets the "peak_rpm" field.
func (_u *PeakUsageUpdate) SetPeakRpm(v int) *PeakUsageUpdate {
	_u.mutation.ResetPeakRpm()
	_u.mutation.SetPeakRpm(v)
	return _u
}

// SetNillablePeakRpm sets the "peak_rpm" field if the given value is not nil.
func (_u *PeakUsageUpdate) SetNillablePeakRpm(v *int) *PeakUsageUpdate {
	if v != nil {
		_u.SetPeakRpm(*v)
	}
	return _u
}

// AddPeakRpm adds value to the "peak_rpm" field.
func (_u *PeakUsageUpdate) AddPeakRpm(v int) *PeakUsageUpdate {
	_u.mutation.AddPeakRpm(v)
	return _u
}

// SetResetAt sets the "reset_at" field.
func (_u *PeakUsageUpdate) SetResetAt(v time.Time) *PeakUsageUpdate {
	_u.mutation.SetResetAt(v)
	return _u
}

// SetNillableResetAt sets the "reset_at" field if the given value is not nil.
func (_u *PeakUsageUpdate) SetNillableResetAt(v *time.Time) *PeakUsageUpdate {
	if v != nil {
		_u.SetResetAt(*v)
	}
	return _u
}

// ClearResetAt clears the value of the "reset_at" field.
func (_u *PeakUsageUpdate) ClearResetAt() *PeakUsageUpdate {
	_u.mutation.ClearResetAt()
	return _u
}

// Mutation returns the PeakUsageMutation object of the builder.
func (_u *PeakUsageUpdate) Mutation() *PeakUsageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PeakUsageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PeakUsageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PeakUsageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PeakUsageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PeakUsageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := peakusage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PeakUsageUpdate) check() error {
	if v, ok := _u.mutation.EntityType(); ok {
		if err := peakusage.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "PeakUsage.entity_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntityID(); ok {
		if err := peakusage.EntityIDValidator(v); err != nil {
			return &ValidationError{Name: "entity_id", err: fmt.Errorf(`ent: validator failed for field "PeakUsage.entity_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PeakConcurrency(); ok {
		if err := peakusage.PeakConcurrencyValidator(v); err != nil {
			return &ValidationError{Name: "peak_concurrency", err: fmt.Errorf(`ent: validator failed for field "PeakUsage.peak_concurrency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PeakSessions(); ok {
		if err := peakusage.PeakSessionsValidator(v); err != nil {
			return &ValidationError{Name: "peak_sessions", err: fmt.Errorf(`ent: validator failed for field "PeakUsage.peak_sessions": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PeakRpm(); ok {
		if err := peakusage.PeakRpmValidator(v); err != nil {
			return &ValidationError{Name: "peak_rpm", err: fmt.Errorf(`ent: validator failed for field "PeakUsage.peak_rpm": %w`, err)}
		}
	}
	return nil
}

func (_u *PeakUsageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(peakusage.Table, peakusage.Columns, sqlgraph.NewFieldSpec(peakusage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(peakusage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(peakusage.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(peakusage.FieldEntityID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntityID(); ok {
		_spec.AddField(peakusage.FieldEntityID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PeakConcurrency(); ok {
		_spec.SetField(peakusage.FieldPeakConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPeakConcurrency(); ok {
		_spec.AddField(peakusage.FieldPeakConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PeakSessions(); ok {
		_spec.SetField(peakusage.FieldPeakSessions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPeakSessions(); ok {
		_spec.AddField(peakusage.FieldPeakSessions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PeakRpm(); ok {
		_spec.SetField(peakusage.FieldPeakRpm, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPeakRpm(); ok {
		_spec.AddField(peakusage.FieldPeakRpm, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResetAt(); ok {
		_spec.SetField(peakusage.FieldResetAt, field.TypeTime, value)
	}
	if _u.mutation.ResetAtCleared() {
		_spec.ClearField(peakusage.FieldResetAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{peakusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PeakUsageUpdateOne is the builder for updating a single PeakUsage entity.
type PeakUsageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PeakUsageMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PeakUsageUpdateOne) SetUpdatedAt(v time.Time) *PeakUsageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *PeakUsageUpdateOne) SetEntityType(v string) *PeakUsageUpdateOne {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *PeakUsageUpdateOne) SetNillableEntityType(v *string) *PeakUsageUpdateOne {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *PeakUsageUpdateOne) SetEntityID(v int64) *PeakUsageUpdateOne {
	_u.mutation.ResetEntityID()
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *PeakUsageUpdateOne) SetNillableEntityID(v *int64) *PeakUsageUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// AddEntityID adds value to the "entity_id" field.
func (_u *PeakUsageUpdateOne) AddEntityID(v int64) *PeakUsageUpdateOne {
	_u.mutation.AddEntityID(v)
	return _u
}

// SetPeakConcurrency sets the "peak_concurrency" field.
func (_u *PeakUsageUpdateOne) SetPeakConcurrency(v int) *PeakUsageUpdateOne {
	_u.mutation.ResetPeakConcurrency()
	_u.mutation.SetPeakConcurrency(v)
	return _u
}

// SetNillablePeakConcurrency sets the "peak_concurrency" field if the given value is not nil.
func (_u *PeakUsageUpdateOne) SetNillablePeakConcurrency(v *int) *PeakUsageUpdateOne {
	if v != nil {
		_u.SetPeakConcurrency(*v)
	}
	return _u
}

// AddPeakConcurrency adds value to the "peak_concurrency" field.
func (_u *PeakUsageUpdateOne) AddPeakConcurrency(v int) *PeakUsageUpdateOne {
	_u.mutation.AddPeakConcurrency(v)
	return _u
}

// SetPeakSessions sets the "peak_sessions" field.
func (_u *PeakUsageUpdateOne) SetPeakSessions(v int) *PeakUsageUpdateOne {
	_u.mutation.ResetPeakSessions()
	_u.mutation.SetPeakSessions(v)
	return _u
}

// SetNillablePeakSessions sets the "peak_sessions" field if the given value is not nil.
func (_u *PeakUsageUpdateOne) SetNillablePeakSessions(v *int) *PeakUsageUpdateOne {
	if v != nil {
		_u.SetPeakSessions(*v)
	}
	return _u
}

// AddPeakSessions adds value to the "peak_sessions" field.
func (_u *PeakUsageUpdateOne) AddPeakSessions(v int) *PeakUsageUpdateOne {
	_u.mutation.AddPeakSessions(v)
	return _u
}

// SetPeakRpm sets the "peak_rpm" field.
func (_u *PeakUsageUpdateOne) SetPeakRpm(v int) *PeakUsageUpdateOne {
	_u.mutation.ResetPeakRpm()
	_u.mutation.SetPeakRpm(v)
	return _u
}

// SetNillablePeakRpm sets the "peak_rpm" field if the given value is not nil.
func (_u *PeakUsageUpdateOne) SetNillablePeakRpm(v *int) *PeakUsageUpdateOne {
	if v != nil {
		_u.SetPeakRpm(*v)
	}
	return _u
}

// AddPeakRpm adds value to the "peak_rpm" field.
func (_u *PeakUsageUpdateOne) AddPeakRpm(v int) *PeakUsageUpdateOne {
	_u.mutation.AddPeakRpm(v)
	return _u
}

// SetResetAt sets the "reset_at" field.
func (_u *PeakUsageUpdateOne) SetResetAt(v time.Time) *PeakUsageUpdateOne {
	_u.mutation.SetResetAt(v)
	return _u
}

// SetNillableResetAt sets the "reset_at" field if the given value is not nil.
func (_u *PeakUsageUpdateOne) SetNillableResetAt(v *time.Time) *PeakUsageUpdateOne {
	if v != nil {
		_u.SetResetAt(*v)
	}
	return _u
}

// ClearResetAt clears the value of the "reset_at" field.
func (_u *PeakUsageUpdateOne) ClearResetAt() *PeakUsageUpdateOne {
	_u.mutation.ClearResetAt()
	return _u
}

// Mutation returns the PeakUsageMutation object of the builder.
func (_u *PeakUsageUpdateOne) Mutation() *PeakUsageMutation {
	return _u.mutation
}

// Where appends a list predicates to the PeakUsageUpdate builder.
func (_u *PeakUsageUpdateOne) Where(ps ...predicate.PeakUsage) *PeakUsageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PeakUsageUpdateOne) Select(field string, fields ...string) *PeakUsageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PeakUsage entity.
func (_u *PeakUsageUpdateOne) Save(ctx context.Context) (*PeakUsage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PeakUsageUpdateOne) SaveX(ctx context.Context) *PeakUsage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PeakUsageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PeakUsageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PeakUsageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := peakusage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PeakUsageUpdateOne) check() error {
	if v, ok := _u.mutation.EntityType(); ok {
		if err := peakusage.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "PeakUsage.entity_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntityID(); ok {
		if err := peakusage.EntityIDValidator(v); err != nil {
			return &ValidationError{Name: "entity_id", err: fmt.Errorf(`ent: validator failed for field "PeakUsage.entity_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PeakConcurrency(); ok {
		if err := peakusage.PeakConcurrencyValidator(v); err != nil {
			return &ValidationError{Name: "peak_concurrency", err: fmt.Errorf(`ent: validator failed for field "PeakUsage.peak_concurrency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PeakSessions(); ok {
		if err := peakusage.PeakSessionsValidator(v); err != nil {
			return &ValidationError{Name: "peak_sessions", err: fmt.Errorf(`ent: validator failed for field "PeakUsage.peak_sessions": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PeakRpm(); ok {
		if err := peakusage.PeakRpmValidator(v); err != nil {
			return &ValidationError{Name: "peak_rpm", err: fmt.Errorf(`ent: validator failed for field "PeakUsage.peak_rpm": %w`, err)}
		}
	}
	return nil
}

func (_u *PeakUsageUpdateOne) sqlSave(ctx context.Context) (_node *PeakUsage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(peakusage.Table, peakusage.Columns, sqlgraph.NewFieldSpec(peakusage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PeakUsage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, peakusage.FieldID)
		for _, f := range fields {
			if !peakusage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != peakusage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(peakusage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(peakusage.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(peakusage.FieldEntityID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntityID(); ok {
		_spec.AddField(peakusage.FieldEntityID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PeakConcurrency(); ok {
		_spec.SetField(peakusage.FieldPeakConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPeakConcurrency(); ok {
		_spec.AddField(peakusage.FieldPeakConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PeakSessions(); ok {
		_spec.SetField(peakusage.FieldPeakSessions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPeakSessions(); ok {
		_spec.AddField(peakusage.FieldPeakSessions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PeakRpm(); ok {
		_spec.SetField(peakusage.FieldPeakRpm, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPeakRpm(); ok {
		_spec.AddField(peakusage.FieldPeakRpm, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResetAt(); ok {
		_spec.SetField(peakusage.FieldResetAt, field.TypeTime, value)
	}
	if _u.mutation.ResetAtCleared() {
		_spec.ClearField(peakusage.FieldResetAt, field.TypeTime)
	}
	_node = &PeakUsage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{peakusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
