// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/peakusage"
)

// PeakUsageCreate is the builder for creating a PeakUsage entity.
type PeakUsageCreate struct {
	config
	mutation *PeakUsageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PeakUsageCreate) SetCreatedAt(v time.Time) *PeakUsageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PeakUsageCreate) SetNillableCreatedAt(v *time.Time) *PeakUsageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PeakUsageCreate) SetUpdatedAt(v time.Time) *PeakUsageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PeakUsageCreate) SetNillableUpdatedAt(v *time.Time) *PeakUsageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEntityType sets the "entity_type" field.
func (_c *PeakUsageCreate) SetEntityType(v string) *PeakUsageCreate {
	_c.mutation.SetEntityType(v)
	return _c
}

// SetEntityID sets the "entity_id" field.
func (_c *PeakUsageCreate) SetEntityID(v int64) *PeakUsageCreate {
	_c.mutation.SetEntityID(v)
	return _c
}

// SetPeakConcurrency sets the "peak_concurrency" field.
func (_c *PeakUsageCreate) SetPeakConcurrency(v int) *PeakUsageCreate {
	_c.mutation.SetPeakConcurrency(v)
	return _c
}

// SetNillablePeakConcurrency sets the "peak_concurrency" field if the given value is not nil.
func (_c *PeakUsageCreate) SetNillablePeakConcurrency(v *int) *PeakUsageCreate {
	if v != nil {
		_c.SetPeakConcurrency(*v)
	}
	return _c
}

// SetPeakSessions sets the "peak_sessions" field.
func (_c *PeakUsageCreate) SetPeakSessions(v int) *PeakUsageCreate {
	_c.mutation.SetPeakSessions(v)
	return _c
}

// SetNillablePeakSessions sets the "peak_sessions" field if the given value is not nil.
func (_c *PeakUsageCreate) SetNillablePeakSessions(v *int) *PeakUsageCreate {
	if v != nil {
		_c.SetPeakSessions(*v)
	}
	return _c
}

// SetPeakRpm sets the "peak_rpm" field.
func (_c *PeakUsageCreate) SetPeakRpm(v int) *PeakUsageCreate {
	_c.mutation.SetPeakRpm(v)
	return _c
}

// SetNillablePeakRpm sets the "peak_rpm" field if the given value is not nil.
func (_c *PeakUsageCreate) SetNillablePeakRpm(v *int) *PeakUsageCreate {
	if v != nil {
		_c.SetPeakRpm(*v)
	}
	return _c
}

// SetResetAt sets the "reset_at" field.
func (_c *PeakUsageCreate) SetResetAt(v time.Time) *PeakUsageCreate {
	_c.mutation.SetResetAt(v)
	return _c
}

// SetNillableResetAt sets the "reset_at" field if the given value is not nil.
func (_c *PeakUsageCreate) SetNillableResetAt(v *time.Time) *PeakUsageCreate {
	if v != nil {
		_c.SetResetAt(*v)
	}
	return _c
}

// Mutation returns the PeakUsageMutation object of the builder.
func (_c *PeakUsageCreate) Mutation() *PeakUsageMutation {
	return _c.mutation
}

// Save creates the PeakUsage in the database.
func (_c *PeakUsageCreate) Save(ctx context.Context) (*PeakUsage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PeakUsageCreate) SaveX(ctx context.Context) *PeakUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PeakUsageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PeakUsageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PeakUsageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := peakusage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := peakusage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.PeakConcurrency(); !ok {
		v := peakusage.DefaultPeakConcurrency
		_c.mutation.SetPeakConcurrency(v)
	}
	if _, ok := _c.mutation.PeakSessions(); !ok {
		v := peakusage.DefaultPeakSessions
		_c.mutation.SetPeakSessions(v)
	}
	if _, ok := _c.mutation.PeakRpm(); !ok {
		v := peakusage.DefaultPeakRpm
		_c.mutation.SetPeakRpm(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PeakUsageCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PeakUsage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PeakUsage.updated_at"`)}
	}
	if _, ok := _c.mutation.EntityType(); !ok {
		return &ValidationError{Name: "entity_type", err: errors.New(`ent: missing required field "PeakUsage.entity_type"`)}
	}
	if v, ok := _c.mutation.EntityType(); ok {
		if err := peakusage.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "PeakUsage.entity_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EntityID(); !ok {
		return &ValidationError{Name: "entity_id", err: errors.New(`ent: missing required field "PeakUsage.entity_id"`)}
	}
	if v, ok := _c.mutation.EntityID(); ok {
		if err := peakusage.EntityIDValidator(v); err != nil {
			return &ValidationError{Name: "entity_id", err: fmt.Errorf(`ent: validator failed for field "PeakUsage.entity_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PeakConcurrency(); !ok {
		return &ValidationError{Name: "peak_concurrency", err: errors.New(`ent: missing required field "PeakUsage.peak_concurrency"`)}
	}
	if v, ok := _c.mutation.PeakConcurrency(); ok {
		if err := peakusage.PeakConcurrencyValidator(v); err != nil {
			return &ValidationError{Name: "peak_concurrency", err: fmt.Errorf(`ent: validator failed for field "PeakUsage.peak_concurrency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PeakSessions(); !ok {
		return &ValidationError{Name: "peak_sessions", err: errors.New(`ent: missing required field "PeakUsage.peak_sessions"`)}
	}
	if v, ok := _c.mutation.PeakSessions(); ok {
		if err := peakusage.PeakSessionsValidator(v); err != nil {
			return &ValidationError{Name: "peak_sessions", err: fmt.Errorf(`ent: validator failed for field "PeakUsage.peak_sessions": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PeakRpm(); !ok {
		return &ValidationError{Name: "peak_rpm", err: errors.New(`ent: missing required field "PeakUsage.peak_rpm"`)}
	}
	if v, ok := _c.mutation.PeakRpm(); ok {
		if err := peakusage.PeakRpmValidator(v); err != nil {
			return &ValidationError{Name: "peak_rpm", err: fmt.Errorf(`ent: validator failed for field "PeakUsage.peak_rpm": %w`, err)}
		}
	}
	return nil
}

func (_c *PeakUsageCreate) sqlSave(ctx context.Context) (*PeakUsage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PeakUsageCreate) createSpec() (*PeakUsage, *sqlgraph.CreateSpec) {
	var (
		_node = &PeakUsage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(peakusage.Table, sqlgraph.NewFieldSpec(peakusage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(peakusage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(peakusage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.EntityType(); ok {
		_spec.SetField(peakusage.FieldEntityType, field.TypeString, value)
		_node.EntityType = value
	}
	if value, ok := _c.mutation.EntityID(); ok {
		_spec.SetField(peakusage.FieldEntityID, field.TypeInt64, value)
		_node.EntityID = value
	}
	if value, ok := _c.mutation.PeakConcurrency(); ok {
		_spec.SetField(peakusage.FieldPeakConcurrency, field.TypeInt, value)
		_node.PeakConcurrency = value
	}
	if value, ok := _c.mutation.PeakSessions(); ok {
		_spec.SetField(peakusage.FieldPeakSessions, field.TypeInt, value)
		_node.PeakSessions = value
	}
	if value, ok := _c.mutation.PeakRpm(); ok {
		_spec.SetField(peakusage.FieldPeakRpm, field.TypeInt, value)
		_node.PeakRpm = value
	}
	if value, ok := _c.mutation.ResetAt(); ok {
		_spec.SetField(peakusage.FieldResetAt, field.TypeTime, value)
		_node.ResetAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PeakUsage.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PeakUsageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PeakUsageCreate) OnConflict(opts ...sql.ConflictOption) *PeakUsageUpsertOne {
	_c.conflict = opts
	return &PeakUsageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PeakUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PeakUsageCreate) OnConflictColumns(columns ...string) *PeakUsageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PeakUsageUpsertOne{
		create: _c,
	}
}

type (
	// PeakUsageUpsertOne is the builder for "upsert"-ing
	//  one PeakUsage node.
	PeakUsageUpsertOne struct {
		create *PeakUsageCreate
	}

	// PeakUsageUpsert is the "OnConflict" setter.
	PeakUsageUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PeakUsageUpsert) SetUpdatedAt(v time.Time) *PeakUsageUpsert {
	u.Set(peakusage.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PeakUsageUpsert) UpdateUpdatedAt() *PeakUsageUpsert {
	u.SetExcluded(peakusage.FieldUpdatedAt)
	return u
}

// SetEntityType sets the "entity_type" field.
func (u *PeakUsageUpsert) SetEntityType(v string) *PeakUsageUpsert {
	u.Set(peakusage.FieldEntityType, v)
	return u
}

// UpdateEntityType sets the "entity_type" field to the value that was provided on create.
func (u *PeakUsageUpsert) UpdateEntityType() *PeakUsageUpsert {
	u.SetExcluded(peakusage.FieldEntityType)
	return u
}

// SetEntityID sets the "entity_id" field.
func (u *PeakUsageUpsert) SetEntityID(v int64) *PeakUsageUpsert {
	u.Set(peakusage.FieldEntityID, v)
	return u
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *PeakUsageUpsert) UpdateEntityID() *PeakUsageUpsert {
	u.SetExcluded(peakusage.FieldEntityID)
	return u
}

// AddEntityID adds v to the "entity_id" field.
func (u *PeakUsageUpsert) AddEntityID(v int64) *PeakUsageUpsert {
	u.Add(peakusage.FieldEntityID, v)
	return u
}

// SetPeakConcurrency sets the "peak_concurrency" field.
func (u *PeakUsageUpsert) SetPeakConcurrency(v int) *PeakUsageUpsert {
	u.Set(peakusage.FieldPeakConcurrency, v)
	return u
}

// UpdatePeakConcurrency sets the "peak_concurrency" field to the value that was provided on create.
func (u *PeakUsageUpsert) UpdatePeakConcurrency() *PeakUsageUpsert {
	u.SetExcluded(peakusage.FieldPeakConcurrency)
	return u
}

// AddPeakConcurrency adds v to the "peak_concurrency" field.
func (u *PeakUsageUpsert) AddPeakConcurrency(v int) *PeakUsageUpsert {
	u.Add(peakusage.FieldPeakConcurrency, v)
	return u
}

// SetPeakSessions sets the "peak_sessions" field.
func (u *PeakUsageUpsert) SetPeakSessions(v int) *PeakUsageUpsert {
	u.Set(peakusage.FieldPeakSessions, v)
	return u
}

// UpdatePeakSessions sets the "peak_sessions" field to the value that was provided on create.
func (u *PeakUsageUpsert) UpdatePeakSessions() *PeakUsageUpsert {
	u.SetExcluded(peakusage.FieldPeakSessions)
	return u
}

// AddPeakSessions adds v to the "peak_sessions" field.
func (u *PeakUsageUpsert) AddPeakSessions(v int) *PeakUsageUpsert {
	u.Add(peakusage.FieldPeakSessions, v)
	return u
}

// SetPeakRpm sets the "peak_rpm" field.
func (u *PeakUsageUpsert) SetPeakRpm(v int) *PeakUsageUpsert {
	u.Set(peakusage.FieldPeakRpm, v)
	return u
}

// UpdatePeakRpm sets the "peak_rpm" field to the value that was provided on create.
func (u *PeakUsageUpsert) UpdatePeakRpm() *PeakUsageUpsert {
	u.SetExcluded(peakusage.FieldPeakRpm)
	return u
}

// AddPeakRpm adds v to the "peak_rpm" field.
func (u *PeakUsageUpsert) AddPeakRpm(v int) *PeakUsageUpsert {
	u.Add(peakusage.FieldPeakRpm, v)
	return u
}

// SetResetAt sets the "reset_at" field.
func (u *PeakUsageUpsert) SetResetAt(v time.Time) *PeakUsageUpsert {
	u.Set(peakusage.FieldResetAt, v)
	return u
}

// UpdateResetAt sets the "reset_at" field to the value that was provided on create.
func (u *PeakUsageUpsert) UpdateResetAt() *PeakUsageUpsert {
	u.SetExcluded(peakusage.FieldResetAt)
	return u
}

// ClearResetAt clears the value of the "reset_at" field.
func (u *PeakUsageUpsert) ClearResetAt() *PeakUsageUpsert {
	u.SetNull(peakusage.FieldResetAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PeakUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PeakUsageUpsertOne) UpdateNewValues() *PeakUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(peakusage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PeakUsage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PeakUsageUpsertOne) Ignore() *PeakUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PeakUsageUpsertOne) DoNothing() *PeakUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PeakUsageCreate.OnConflict
// documentation for more info.
func (u *PeakUsageUpsertOne) Update(set func(*PeakUsageUpsert)) *PeakUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PeakUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PeakUsageUpsertOne) SetUpdatedAt(v time.Time) *PeakUsageUpsertOne {
	return u.Update(func(s *PeakUsageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PeakUsageUpsertOne) UpdateUpdatedAt() *PeakUsageUpsertOne {
	return u.Update(func(s *PeakUsageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEntityType sets the "entity_type" field.
func (u *PeakUsageUpsertOne) SetEntityType(v string) *PeakUsageUpsertOne {
	return u.Update(func(s *PeakUsageUpsert) {
		s.SetEntityType(v)
	})
}

// UpdateEntityType sets the "entity_type" field to the value that was provided on create.
func (u *PeakUsageUpsertOne) UpdateEntityType() *PeakUsageUpsertOne {
	return u.Update(func(s *PeakUsageUpsert) {
		s.UpdateEntityType()
	})
}

// SetEntityID sets the "entity_id" field.
func (u *PeakUsageUpsertOne) SetEntityID(v int64) *PeakUsageUpsertOne {
	return u.Update(func(s *PeakUsageUpsert) {
		s.SetEntityID(v)
	})
}

// AddEntityID adds v to the "entity_id" field.
func (u *PeakUsageUpsertOne) AddEntityID(v int64) *PeakUsageUpsertOne {
	return u.Update(func(s *PeakUsageUpsert) {
		s.AddEntityID(v)
	})
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *PeakUsageUpsertOne) UpdateEntityID() *PeakUsageUpsertOne {
	return u.Update(func(s *PeakUsageUpsert) {
		s.UpdateEntityID()
	})
}

// SetPeakConcurrency sets the "peak_concurrency" field.
func (u *PeakUsageUpsertOne) SetPeakConcurrency(v int) *PeakUsageUpsertOne {
	return u.Update(func(s *PeakUsageUpsert) {
		s.SetPeakConcurrency(v)
	})
}

// AddPeakConcurrency adds v to the "peak_concurrency" field.
func (u *PeakUsageUpsertOne) AddPeakConcurrency(v int) *PeakUsageUpsertOne {
	return u.Update(func(s *PeakUsageUpsert) {
		s.AddPeakConcurrency(v)
	})
}

// UpdatePeakConcurrency sets the "peak_concurrency" field to the value that was provided on create.
func (u *PeakUsageUpsertOne) UpdatePeakConcurrency() *PeakUsageUpsertOne {
	return u.Update(func(s *PeakUsageUpsert) {
		s.UpdatePeakConcurrency()
	})
}

// SetPeakSessions sets the "peak_sessions" field.
func (u *PeakUsageUpsertOne) SetPeakSessions(v int) *PeakUsageUpsertOne {
	return u.Update(func(s *PeakUsageUpsert) {
		s.SetPeakSessions(v)
	})
}

// AddPeakSessions adds v to the "peak_sessions" field.
func (u *PeakUsageUpsertOne) AddPeakSessions(v int) *PeakUsageUpsertOne {
	return u.Update(func(s *PeakUsageUpsert) {
		s.AddPeakSessions(v)
	})
}

// UpdatePeakSessions sets the "peak_sessions" field to the value that was provided on create.
func (u *PeakUsageUpsertOne) UpdatePeakSessions() *PeakUsageUpsertOne {
	return u.Update(func(s *PeakUsageUpsert) {
		s.UpdatePeakSessions()
	})
}

// SetPeakRpm sets the "peak_rpm" field.
func (u *PeakUsageUpsertOne) SetPeakRpm(v int) *PeakUsageUpsertOne {
	return u.Update(func(s *PeakUsageUpsert) {
		s.SetPeakRpm(v)
	})
}

// AddPeakRpm adds v to the "peak_rpm" field.
func (u *PeakUsageUpsertOne) AddPeakRpm(v int) *PeakUsageUpsertOne {
	return u.Update(func(s *PeakUsageUpsert) {
		s.AddPeakRpm(v)
	})
}

// UpdatePeakRpm sets the "peak_rpm" field to the value that was provided on create.
func (u *PeakUsageUpsertOne) UpdatePeakRpm() *PeakUsageUpsertOne {
	return u.Update(func(s *PeakUsageUpsert) {
		s.UpdatePeakRpm()
	})
}

// SetResetAt sets the "reset_at" field.
func (u *PeakUsageUpsertOne) SetResetAt(v time.Time) *PeakUsageUpsertOne {
	return u.Update(func(s *PeakUsageUpsert) {
		s.SetResetAt(v)
	})
}

// UpdateResetAt sets the "reset_at" field to the value that was provided on create.
func (u *PeakUsageUpsertOne) UpdateResetAt() *PeakUsageUpsertOne {
	return u.Update(func(s *PeakUsageUpsert) {
		s.UpdateResetAt()
	})
}

// ClearResetAt clears the value of the "reset_at" field.
func (u *PeakUsageUpsertOne) ClearResetAt() *PeakUsageUpsertOne {
	return u.Update(func(s *PeakUsageUpsert) {
		s.ClearResetAt()
	})
}

// Exec executes the query.
func (u *PeakUsageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PeakUsageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PeakUsageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PeakUsageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PeakUsageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PeakUsageCreateBulk is the builder for creating many PeakUsage entities in bulk.
type PeakUsageCreateBulk struct {
	config
	err      error
	builders []*PeakUsageCreate
	conflict []sql.ConflictOption
}

// Save creates the PeakUsage entities in the database.
func (_c *PeakUsageCreateBulk) Save(ctx context.Context) ([]*PeakUsage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PeakUsage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PeakUsageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PeakUsageCreateBulk) SaveX(ctx context.Context) []*PeakUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PeakUsageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PeakUsageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PeakUsage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PeakUsageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PeakUsageCreateBulk) OnConflict(opts ...sql.ConflictOption) *PeakUsageUpsertBulk {
	_c.conflict = opts
	return &PeakUsageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PeakUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PeakUsageCreateBulk) OnConflictColumns(columns ...string) *PeakUsageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PeakUsageUpsertBulk{
		create: _c,
	}
}

// PeakUsageUpsertBulk is the builder for "upsert"-ing
// a bulk of PeakUsage nodes.
type PeakUsageUpsertBulk struct {
	create *PeakUsageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PeakUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PeakUsageUpsertBulk) UpdateNewValues() *PeakUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(peakusage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PeakUsage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PeakUsageUpsertBulk) Ignore() *PeakUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PeakUsageUpsertBulk) DoNothing() *PeakUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PeakUsageCreateBulk.OnConflict
// documentation for more info.
func (u *PeakUsageUpsertBulk) Update(set func(*PeakUsageUpsert)) *PeakUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PeakUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PeakUsageUpsertBulk) SetUpdatedAt(v time.Time) *PeakUsageUpsertBulk {
	return u.Update(func(s *PeakUsageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PeakUsageUpsertBulk) UpdateUpdatedAt() *PeakUsageUpsertBulk {
	return u.Update(func(s *PeakUsageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEntityType sets the "entity_type" field.
func (u *PeakUsageUpsertBulk) SetEntityType(v string) *PeakUsageUpsertBulk {
	return u.Update(func(s *PeakUsageUpsert) {
		s.SetEntityType(v)
	})
}

// UpdateEntityType sets the "entity_type" field to the value that was provided on create.
func (u *PeakUsageUpsertBulk) UpdateEntityType() *PeakUsageUpsertBulk {
	return u.Update(func(s *PeakUsageUpsert) {
		s.UpdateEntityType()
	})
}

// SetEntityID sets the "entity_id" field.
func (u *PeakUsageUpsertBulk) SetEntityID(v int64) *PeakUsageUpsertBulk {
	return u.Update(func(s *PeakUsageUpsert) {
		s.SetEntityID(v)
	})
}

// AddEntityID adds v to the "entity_id" field.
func (u *PeakUsageUpsertBulk) AddEntityID(v int64) *PeakUsageUpsertBulk {
	return u.Update(func(s *PeakUsageUpsert) {
		s.AddEntityID(v)
	})
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *PeakUsageUpsertBulk) UpdateEntityID() *PeakUsageUpsertBulk {
	return u.Update(func(s *PeakUsageUpsert) {
		s.UpdateEntityID()
	})
}

// SetPeakConcurrency sets the "peak_concurrency" field.
func (u *PeakUsageUpsertBulk) SetPeakConcurrency(v int) *PeakUsageUpsertBulk {
	return u.Update(func(s *PeakUsageUpsert) {
		s.SetPeakConcurrency(v)
	})
}

// AddPeakConcurrency adds v to the "peak_concurrency" field.
func (u *PeakUsageUpsertBulk) AddPeakConcurrency(v int) *PeakUsageUpsertBulk {
	return u.Update(func(s *PeakUsageUpsert) {
		s.AddPeakConcurrency(v)
	})
}

// UpdatePeakConcurrency sets the "peak_concurrency" field to the value that was provided on create.
func (u *PeakUsageUpsertBulk) UpdatePeakConcurrency() *PeakUsageUpsertBulk {
	return u.Update(func(s *PeakUsageUpsert) {
		s.UpdatePeakConcurrency()
	})
}

// SetPeakSessions sets the "peak_sessions" field.
func (u *PeakUsageUpsertBulk) SetPeakSessions(v int) *PeakUsageUpsertBulk {
	return u.Update(func(s *PeakUsageUpsert) {
		s.SetPeakSessions(v)
	})
}

// AddPeakSessions adds v to the "peak_sessions" field.
func (u *PeakUsageUpsertBulk) AddPeakSessions(v int) *PeakUsageUpsertBulk {
	return u.Update(func(s *PeakUsageUpsert) {
		s.AddPeakSessions(v)
	})
}

// UpdatePeakSessions sets the "peak_sessions" field to the value that was provided on create.
func (u *PeakUsageUpsertBulk) UpdatePeakSessions() *PeakUsageUpsertBulk {
	return u.Update(func(s *PeakUsageUpsert) {
		s.UpdatePeakSessions()
	})
}

// SetPeakRpm sets the "peak_rpm" field.
func (u *PeakUsageUpsertBulk) SetPeakRpm(v int) *PeakUsageUpsertBulk {
	return u.Update(func(s *PeakUsageUpsert) {
		s.SetPeakRpm(v)
	})
}

// AddPeakRpm adds v to the "peak_rpm" field.
func (u *PeakUsageUpsertBulk) AddPeakRpm(v int) *PeakUsageUpsertBulk {
	return u.Update(func(s *PeakUsageUpsert) {
		s.AddPeakRpm(v)
	})
}

// UpdatePeakRpm sets the "peak_rpm" field to the value that was provided on create.
func (u *PeakUsageUpsertBulk) UpdatePeakRpm() *PeakUsageUpsertBulk {
	return u.Update(func(s *PeakUsageUpsert) {
		s.UpdatePeakRpm()
	})
}

// SetResetAt sets the "reset_at" field.
func (u *PeakUsageUpsertBulk) SetResetAt(v time.Time) *PeakUsageUpsertBulk {
	return u.Update(func(s *PeakUsageUpsert) {
		s.SetResetAt(v)
	})
}

// UpdateResetAt sets the "reset_at" field to the value that was provided on create.
func (u *PeakUsageUpsertBulk) UpdateResetAt() *PeakUsageUpsertBulk {
	return u.Update(func(s *PeakUsageUpsert) {
		s.UpdateResetAt()
	})
}

// ClearResetAt clears the value of the "reset_at" field.
func (u *PeakUsageUpsertBulk) ClearResetAt() *PeakUsageUpsertBulk {
	return u.Update(func(s *PeakUsageUpsert) {
		s.ClearResetAt()
	})
}

// Exec executes the query.
func (u *PeakUsageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PeakUsageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PeakUsageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PeakUsageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
