// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/peakusage"
)

// PeakUsage is the model entity for the PeakUsage schema.
type PeakUsage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// account or user
	EntityType string `json:"entity_type,omitempty"`
	// EntityID holds the value of the "entity_id" field.
	EntityID int64 `json:"entity_id,omitempty"`
	// PeakConcurrency holds the value of the "peak_concurrency" field.
	PeakConcurrency int `json:"peak_concurrency,omitempty"`
	// PeakSessions holds the value of the "peak_sessions" field.
	PeakSessions int `json:"peak_sessions,omitempty"`
	// PeakRpm holds the value of the "peak_rpm" field.
	PeakRpm int `json:"peak_rpm,omitempty"`
	// ResetAt holds the value of the "reset_at" field.
	ResetAt      *time.Time `json:"reset_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PeakUsage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case peakusage.FieldID, peakusage.FieldEntityID, peakusage.FieldPeakConcurrency, peakusage.FieldPeakSessions, peakusage.FieldPeakRpm:
			values[i] = new(sql.NullInt64)
		case peakusage.FieldEntityType:
			values[i] = new(sql.NullString)
		case peakusage.FieldCreatedAt, peakusage.FieldUpdatedAt, peakusage.FieldResetAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PeakUsage fields.
func (_m *PeakUsage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case peakusage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case peakusage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case peakusage.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case peakusage.FieldEntityType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity_type", values[i])
			} else if value.Valid {
				_m.EntityType = value.String
			}
		case peakusage.FieldEntityID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field entity_id", values[i])
			} else if value.Valid {
				_m.EntityID = value.Int64
			}
		case peakusage.FieldPeakConcurrency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field peak_concurrency", values[i])
			} else if value.Valid {
				_m.PeakConcurrency = int(value.Int64)
			}
		case peakusage.FieldPeakSessions:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field peak_sessions", values[i])
			} else if value.Valid {
				_m.PeakSessions = int(value.Int64)
			}
		case peakusage.FieldPeakRpm:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field peak_rpm", values[i])
			} else if value.Valid {
				_m.PeakRpm = int(value.Int64)
			}
		case peakusage.FieldResetAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reset_at", values[i])
			} else if value.Valid {
				_m.ResetAt = new(time.Time)
				*_m.ResetAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PeakUsage.
// This includes values selected through modifiers, order, etc.
func (_m *PeakUsage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PeakUsage.
// Note that you need to call PeakUsage.Unwrap() before calling this method if this PeakUsage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PeakUsage) Update() *PeakUsageUpdateOne {
	return NewPeakUsageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PeakUsage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PeakUsage) Unwrap() *PeakUsage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PeakUsage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PeakUsage) String() string {
	var builder strings.Builder
	builder.WriteString("PeakUsage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("entity_type=")
	builder.WriteString(_m.EntityType)
	builder.WriteString(", ")
	builder.WriteString("entity_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntityID))
	builder.WriteString(", ")
	builder.WriteString("peak_concurrency=")
	builder.WriteString(fmt.Sprintf("%v", _m.PeakConcurrency))
	builder.WriteString(", ")
	builder.WriteString("peak_sessions=")
	builder.WriteString(fmt.Sprintf("%v", _m.PeakSessions))
	builder.WriteString(", ")
	builder.WriteString("peak_rpm=")
	builder.WriteString(fmt.Sprintf("%v", _m.PeakRpm))
	builder.WriteString(", ")
	if v := _m.ResetAt; v != nil {
		builder.WriteString("reset_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// PeakUsages is a parsable slice of PeakUsage.
type PeakUsages []*PeakUsage
